### ISSUE TITLE
Hitbox is not showing, therefore the colour is not needed.

### ISSUE THREAD

**Issue by rohilpatel15** [COMP2522/project-a-maze-ing#38]
https://github.com/COMP2522/project-a-maze-ing/blob/f65597e4add3c135d8dd28810e8585aaa245cff7/src/main/java/org/bcit/com2522/project/enemy/Wraith.java#L17

**Comment by Nelsonph11** [comment]
When I test the enemy type collisions, I like to have the colour for their hitboxes here so I can track what enemy it is while seeing the interaction between player and enemy hitboxes
