### ISSUE TITLE
Move method requires a little bit of refactoring. Also "// Do nothing" is not needed

### ISSUE THREAD

**Issue by rohilpatel15** [COMP2522/project-a-maze-ing#61]
https://github.com/COMP2522/project-a-maze-ing/blob/f65597e4add3c135d8dd28810e8585aaa245cff7/src/main/java/org/bcit/com2522/project/enemy/Sporadic.java#L54

**Comment by Nelsonph11** [comment]
fixed in wraith redundancy branch
